- hosts: slstaticbase
  user: smartlis
  become: yes
  become_method: sudo
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
    
    - name: install php
      apt:
        name: php
        state: present

    - name: install imagemagick
      apt:
        name: imagemagick
        state: present

    - name: install gcc, php-common, php-imagick, libapache2-mod-php
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - gcc
        - php-common
        - php-imagick
        - libapache2-mod-php

    - name: restart apache service
      service:
        name: apache2
        state: restarted

    - name: Create /var/www/html/test.php file
      file:
        path: /var/www/html/test.php
        state: touch

    - name: Edit /var/www/html/test.php file
      blockinfile:
        path: /var/www/html/test.php
        block: |
          <?php
          phpinfo();
          ?>

    - name: check imagemagick installation
      uri:
        url: http://localhost/test.php
        return_content: yes
      register: webpage

    - name: Fail if imagick is not in the page content
      fail:
      when: "'imagick' not in webpage.content"
